### ISSUE TITLE
[ENH] multiple quantile regression

### ISSUE THREAD

**Issue by Ram0nB** [sktime/skpro#107]
**Is your feature request related to a problem? Please describe.**

For quantile regression, often more than one quantile probability is of interest. However, existing Sklearn compatible quantile regressors always fit and predict a single quantile probability. To the best of my knowdlegde, there is no standardized way to integrate multiple quantile regression with Sktime/Skpro probabilistic prediction methods such as predict_quantiles/predict_intervals.

**Describe the solution you'd like**

New Skpro regressor that wraps multiple quantile regressors and supports probabilistic predictions from wrapped regressors.

**Describe alternatives you've considered**

None, as the proposed solution is already discussed in Sktime issue https://github.com/sktime/sktime/issues/5357

**Comment by fkiraly** [comment]
for reference, the proposed is (in clearer and more precise language) this line in on the wishlist/roadmap #7:

![image](https://github.com/sktime/skpro/assets/7985502/b78af610-30f2-454d-934b-a94c92f704e6)

**Comment by fkiraly** [comment]
maybe out of scope for the current PR; but one question, @Ram0nB - there are different ways to deal with quantile crossing. Should we, and if yes how, take these into account?

**Comment by Ram0nB** [comment]
Good one. We could provide the user a "method" parameter similar to Sktime's Imputer, provide the user a quantile_crossing_callable similar to Sktime's FunctionTransformer, or both. What are your thoughts on this @fkiraly ? Maybe we can open an enhancement issue for this for now?
