### ISSUE TITLE
[ENH] MAPIE interface

### ISSUE THREAD

**Issue by fkiraly** [sktime/skpro#134]
MAPIE is one of the more popular "favourite algorithm" repositories in the probabilistic supervised learning space.

Their scope is more geared towards multiple tasks (incl classification, time series forecasting, etc), whereas `skpro` has a more stringent framework layer imo.

The specific estimator that would be great to interface is the `MapieRegressor`:
https://github.com/scikit-learn-contrib/MAPIE/blob/master/mapie/regression/regression.py

should be straightforward with the extension template.
https://github.com/sktime/skpro/blob/main/extension_templates/regression.py

FYI @gmartinonQM, @thibaultcordier, @LacombeLouis, @vincentblot28, @vtaquet, @SZiane in case there might be interest in close collaboration - I see you are planning to add further models, and you are also following closely sklearn as a design template, so perhaps we should merge base class architectures?

For context, `skpro` is a 2017 package for proba supervised (tabular) regression which is one of the design antecessors of `sktime`. Parts of it became the `sktime` probabilistic forecasting module, now it has been rearchitected using `skbase`. Of course a number of proba supervised regression packages have seen the light of day since 2017.

`sktime` and `skpro` adopt a framework integration philosophy where third party packages can be easily interfaced and used as components in pipelines etc, we manage dependencies on the level of estimators.
https://www.sktime.net/en/stable/

For instance, `skpro` probabilistic tabular regressors can be used in `sktime` probabilistic forecasting pipelines.

**Comment by fkiraly** [comment]
PS: I will be at Inria in the week of November 6, we could talk in person there.

**Comment by fkiraly** [comment]
I've used this as a test case to stress test the estimator dependency management. PR is here: https://github.com/sktime/skpro/pull/136

**Comment by thibaultcordier** [comment]
Hello @fkiraly, we are curious to learn more about your project and what type of close collaboration you envisage with MAPIE. We'll be able to discuss this with you to get a clearer idea of what you're planning, at the end of this week.

**Comment by fkiraly** [comment]
> We'll be able to discuss this with you to get a clearer idea of what you're planning, at the end of this week.

Excellent! Let me know when is convenient. I don't have your email, but mine is public, so we can do some scheduling there? Will be in Paris this week.
