### ISSUE TITLE
[BUG] QPD distribution and `CyclicBoosting` API non-compliance

### ISSUE THREAD

**Issue by fkiraly** [sktime/skpro#190]
@setoguchi-naoki, @FelixWick, I have to apologize in advance for this.

Due to an error in the test logic introduced in an update to class retrieval (see https://github.com/sktime/skpro/pull/189), probability distributions went uncovered for most of your PR's duration.

This is my fault for not noticing, and breaking it in the first place.

Bad news is that the QPD distribution have a few non-compliances:

* `cdf` method
* `mean`, `var`
* subsetting

`CyclicBoosting` as well:

* `_predict_quantiles` arg should be `alpha`, not `quantiles`

Good news is that this has not been released yet, and I was running more tests before the 2.2.0 release, which is what ultimately caught the problem.

I'll simply wait with 2.2.0 until we had time to fix this - happy to help.

For testing locally, you need to depend on the branch #189 until it is merged.

**Comment by fkiraly** [comment]
Mechanically, to remove failurse from `main` while reeabling tests:

* I'll add skip commads for the failing estimators, see https://github.com/sktime/skpro/pull/193
* a PR fixing the remaining non-compliances should remove the skip commands to ensure testing

**Comment by FelixWick** [comment]
@setoguchi-naoki Can you give this a try, please? I can help if you face any issues, of course.

**Comment by fkiraly** [comment]
For `CyclicBoosting`, renaming args seems to have worked: https://github.com/sktime/skpro/pull/195

So we now only need to worry about the QPD distributions.
