### ISSUE TITLE
[ENH] `QPD_B` `mean` and `var` fail due to numeric instability

### ISSUE THREAD

**Issue by fkiraly** [sktime/skpro#257]
`QPD_B` is failing internally, it is substituting 0 or 1 into a logit, which produces nans.

To reproduce, run `check_estimator` on `QPD_B`, it is failing for the supplied examples.

Any ideas where or why, @FelixWick, @setoguchi-naoki?

**Comment by FelixWick** [comment]
We are still calling the extended versions for J-QPD-S and J-QPD-B. Since I have only updated the non-extended to work vectorized, I would suggest to switch to these. (This might also fix this issue.)

**Comment by fkiraly** [comment]
Resolved by https://github.com/sktime/skpro/pull/327
