### ISSUE TITLE
[ENH] dummy supervised regressor

### ISSUE THREAD

**Issue by fkiraly** [sktime/skpro#430]
We should implement a `DummyProbaRegressor` with following strategies:

* `"empirical"` - default (?), simply returns the empirical unweighted distribution of training labels
* `"normal"` - returns a gaussian with empirical variance and mean of training labels

**Comment by fkiraly** [comment]
noting, `predict_var` could be easy to implement - in both strategies, this is the empirical variance, and `predict` is always the mean

**Comment by fkiraly** [comment]
recipe:

* in `fit`, fit an `Empirical` or `Normal` distribution that is *scalar* 
* in `predict_proba`, broadcast the `Normal` or `Empirical`. For `Normal`, it should work just setting the right `index` and `columns` - for `Empirical`, it might be more fiddly - or, one could try using the `Iid` distribution, written for this purpose.

**Comment by julian-fong** [comment]
For the `DummyProbaRegressor` do we just ignore the input feature `X` and only use the labels/targets `y`?

**Comment by julian-fong** [comment]
I am also a bit unfamiliar with the empirical distribution - is something like this looking to be implemented? https://www.statlect.com/asymptotic-theory/empirical-distribution

**Comment by fkiraly** [comment]
> For the `DummyProbaRegressor` do we just ignore the input feature `X` and only use the labels/targets `y`?

yes, that´s the idea

> I am also a bit unfamiliar with the empirical distribution - is something like this looking to be implemented? https://www.statlect.com/asymptotic-theory/empirical-distribution

This exists already, it is the distribution called `Empirical`
