### ISSUE TITLE
[ENH] synchronize dependency checking utilities with `sktime` and `skbase`

### ISSUE THREAD

**Issue by fkiraly** [sktime/skpro#489]
The dependency checking utilities in `utils` should be synchronized with `sktime`, see `utils.dependencies` there, and `skbase`.

The long-term trajectory is deduplication with single location of truth in `skbase`, but this will require equal functionality throughout the three packages, as an intermediate step.

Currently, the `skpro` module - in `utils.validation._dependencies` - is a fork of a much earlier version of the `sktime` module, and is subject to the problem that it imports the packages in order to check presence of dependencies.

This is causing the failures in the test collection phase in https://github.com/sktime/skpro/pull/358, or more generally, in a case where the imported package is faulty, with import causing exceptions (in the case of #358, `arviz`).

@meraldoantonio has committed to sort this out in a separate PR, this should resolve the failures in #358 as well.

**Comment by meraldoantonio** [comment]
> The dependency checking utilities in `utils` should be synchronized with `sktime`, see `utils.dependencies` there, and `skbase`.
> 
> The long-term trajectory is deduplication with single location of truth in `skbase`, but this will require equal functionality throughout the three packages, as an intermediate step.
> 
> Currently, the `skpro` module - in `utils.validation._dependencies` - is a fork of a much earlier version of the `sktime` module, and is subject to the problem that it imports the packages in order to check presence of dependencies.
> 
> This is causing the failures in the test collection phase in #358, or more generally, in a case where the imported package is faulty, with import causing exceptions (in the case of #358, `arviz`).

Hi Franz, opened new PR #490

**Comment by fkiraly** [comment]
Addressed in #490
