### ISSUE TITLE
[BUG] The `cdf` for the `Empirical` distribution returns a dataframe of objects

### ISSUE THREAD

**Issue by Alex-JG3** [sktime/skpro#55]
**Describe the bug**

The `cdf` function for the `Empirical` distribution returns a dataframe of python objects. It should return a dataframe of floats or integers.

**To Reproduce**

```python
>>> import pandas as pd
>>> import numpy as np
>>> from skrpo.distributions.empirical import Empirical
>>> spl_idx = pd.MultiIndex.from_product([[0, 1], [0, 1, 2]], names=["sample", "time"])
>>> spl = pd.DataFrame([[0, 1], [2, 3], [10, 11], [6, 7], [8, 9], [4, 5]], index=spl_idx, columns=["a", "b"])
>>> d = Empirical(spl)
>>> x = pd.DataFrame([[1, 2], [3, 4], [5, 6]], index=pd.Index([0, 1, 2]), columns=pd.Index(['a', 'b']))
>>> d.cdf(x)
     a    b
0  0.5  0.5
1  0.5  0.5
2  0.5  0.5
>>> d.cdf(x).values.dtype
dtype('O')
>>> d.cdf(x).dtypes
a    Float64
b    Float64
```

**Expected behavior**

The dataframe returned from `cdf` should contain floats of integers. I don't think `Float64` is a valid `pandas` datatype - it should be `float64`. Here is an example creating a simple float dataframe.

```
>>> y = pd.DataFrame([[1.0, 2.0], [3.0, 4.0]])
>>> y.dtypes
0    float64
1    float64
dtype: object
>>> y.values.dtype
dtype('float64')
```

**Environment**

Pip freeze.
```
anyio==3.7.1
backoff==2.2.1
certifi==2023.7.22
cfgv==3.4.0
coverage==7.3.0
distlib==0.3.7
exceptiongroup==1.1.3
execnet==2.0.2
filelock==3.12.2
h11==0.14.0
httpcore==0.17.3
httpx==0.24.1
identify==2.5.27
idna==3.4
iniconfig==2.0.0
joblib==1.3.2
nodeenv==1.8.0
numpy==1.24.4
packaging==23.1
pandas==2.0.3
platformdirs==3.10.0
pluggy==1.3.0
pre-commit==3.3.3
pytest==7.4.0
pytest-cov==4.1.0
pytest-randomly==3.15.0
pytest-timeout==2.1.0
pytest-xdist==3.3.1
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
scikit-base==0.5.1
scikit-learn==1.3.0
scipy==1.11.2
six==1.16.0
skpro @ file:///home/alex/documents/skpro
sniffio==1.3.0
threadpoolctl==3.2.0
tomli==2.0.1
tzdata==2023.3
virtualenv==20.24.3
```
OS:
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

**Additional context**

This problem arose when I was trying to write a test to check if `cdf` is the inverse of `ppf`.

**Comment by Alex-JG3** [comment]
@fkiraly, just tagging you incase you have not seen this.

It looks like the pandas' `convert_dtypes` function might be the problem.

https://github.com/sktime/skpro/blob/main/skpro/distributions/empirical.py#L129

Here is an example that is similar to the for loop here https://github.com/sktime/skpro/blob/main/skpro/distributions/empirical.py#L118.

```python
>>> import pandas as pd
>>> df = pd.DataFrame(index=[1, 2, 3], columns=['a', 'b'])
>>> df.dtypes
a    object
b    object
dtype: object
>>> df.loc[1, 'a'] = 1.5
>>> df.loc[2, 'b'] = 1.6
>>> df
     a    b
1  1.5  NaN
2  NaN  1.6
3  NaN  NaN
>>> df.dtypes
a    object
b    object
dtype: object
>>> df_conv = df.convert_dtypes()
>>> df_conv.dtypes
a    Float64
b    Float64
dtype: object
>>> df_conv.values
array([[1.5, <NA>],
       [<NA>, 1.6],
       [<NA>, <NA>]], dtype=object)
```
So using `convert_dtypes` on a dataframe containing `objects` seems to give some unexpected datatypes. The resulting numpy array `df_conv.values` also has type `object` here which makes it difficult to work with.

Avoiding `convert_dtypes` might solve the issue.

**Comment by fkiraly** [comment]
Yes, I did not see this - was starting a new job so busy with admin, moving, etc. Also you opened this first in skbase, by accident (all fixed).

Would you like to fix this, or should I? If you are already working on tests, might be more synergistic if you do.

I'm busy with making the refactored version of the package "feature complete" for the presentation in mid-Sep and interoperable with sktime.

**Comment by Alex-JG3** [comment]
> was starting a new job so busy with admin, moving, etc.

Good luck with your new job!

> Would you like to fix this, or should I? 

Yes I am happy to fix this.

**Comment by fkiraly** [comment]
> Yes I am happy to fix this.

thx!
